## Core python programming regards to the datascience

In [1]:
#http://localhost:8888/notebooks/NAREH%20IT/AMXWAM_C2_DataStructures.ipynb#Core-python-programming-regards-to-the-datascience# =============TYPES OF VARIABLES/data types ( INT , FLOAT, STRING, BOOL)================

# int - 
x=2
x

2

In [2]:
x

2

In [3]:
type(x) 

int

In [4]:
# float -
y = 4.6 

In [5]:
y

4.6

In [6]:
type(y) 

float

In [7]:
# string - 
z = 'hello'

In [8]:
z

'hello'

In [9]:
z1 = "hi"

In [10]:

z1
print(z1) 
type(z1) 

hi


str

In [11]:
# bool // logical -
g = True
g

True

In [12]:
m1 = False + True
m1

1

In [13]:
g 

True

In [14]:
a = True + True
a

2

In [15]:
i = "False"

In [16]:
i

'False'

In [17]:
a2=45

In [18]:
b2=56

In [19]:
a2
#b2

45

In [20]:
print(a2)
b2

45


56

In [21]:
# ================== USING VARIABLES =======================

# Arithmetic -
A = 10
B = 5

In [22]:
C = A + B
C

15

In [23]:
D = B/A
D

0.5

In [24]:
E = A*B
E

50

In [25]:
F = B-A
F

-5

In [26]:
C

15

In [27]:
D


0.5

In [28]:
E

50

In [29]:
F

-5

In [30]:
# why is it better to use print() // (ANS) - all o/p will display one time 
print(C)
print(D)
print(E)
print(F)

15
0.5
50
-5


In [31]:
# How to run the square root operation - 
import math # math is the package which you are importing

In [32]:
math.sqrt(25) # 16 is the argument of the sqrt function

5.0

In [33]:
A = 10

In [34]:
math.sqrt(A) #A=10 which we declare at begining

3.1622776601683795

In [35]:
round(math.sqrt(A)) 

3

In [36]:
# lets working with string 
greeting = 'hello'
name = " aspired data scientitst"

In [37]:
message = greeting +  name
message

'hello aspired data scientitst'

In [38]:
name = " nareshIT"
message = greeting + name
message

'hello nareshIT'

In [39]:
# ================ BOOL VARIABLES AND OPERATORS ====================
4<5

True

In [40]:
10>100

False

In [ ]:
# <
# >
# <=
# >=
# and
# or
# not

In [41]:
result = 4<5

In [42]:
result

True

In [43]:
type(result) 

bool

In [44]:
result2 = 5>1

In [45]:
result2

True

In [46]:
result3 = not(5>1) 

In [47]:
result3

False

In [48]:
result

True

In [49]:
result2

True

In [50]:
result3

False

In [51]:
result or result2 or result3 

True

In [52]:
result or result3 or result2  

True

In [53]:
result2 and result3

False

In [54]:
result2 or result3

True

In [55]:
result and result2 or result3

True

In [ ]:
# =================== WHILE LOOP =========================

# what is while loop why used for - lets discuss that--- 

#while(condition){   # checking the condition if the conditiong is true then execute the loop and it keep continue thats why it called as loop
#     executable code1                        # if the condition is false then print to code4 
#     executable code2
#     executable code3
# }
# executable code4

In [ ]:
# === python is indentation based program & no need to required 
# very important you have to check the indentataion & need to maintain properly
# python there is no curly braces
# --------------------------------------------------------------

#while condition:
#    executable code1
#    executable code2
#    executable code3
#executable code4

In [56]:
num = 12
while num<11: 
    print(num)
    num = num+1
print('END OF THE PROGRAM')

END OF THE PROGRAM


In [1]:
count = 13
while count<12:
    print(count)
    count = count + 1
print("End the loop")

End the loop


In [ ]:
#count = 22  #how to print infinite loop
#while count>12: # 22>12
#    print(count)
#    count = count + 1
#print("End the loop")

In [3]:
# ==================== FOR LOOP ==============================

# i define as iteration
for i in range(5):  # while loop we check the  condition
    print('Hello python') 

Hello python
Hello python
Hello python
Hello python
Hello python


In [4]:
for j in range(5):
    print("Hello python:", j)
    print('welcome to naresh') 

Hello python: 0
welcome to naresh
Hello python: 1
welcome to naresh
Hello python: 2
welcome to naresh
Hello python: 3
welcome to naresh
Hello python: 4
welcome to naresh


In [5]:
for i in range(7):
    print("Hello python:",i) 
    #print("Hello python:",i)

Hello python: 0
Hello python: 1
Hello python: 2
Hello python: 3
Hello python: 4
Hello python: 5
Hello python: 6


In [6]:
#Another way
mylist = [10,100,1000,2000] 
type(mylist)

list

In [7]:
mylist[:3]  

[10, 100, 1000]

In [32]:
mylist

[10, 100, 1000, 2000]

In [9]:
mylist[::-1]  

[2000, 1000, 100, 10]

In [10]:
mylist

[10, 100, 1000, 2000]

In [11]:
mylist[:-1] 

[10, 100, 1000]

In [12]:
mylist

[10, 100, 1000, 2000]

In [13]:
mylist[:-2]   

[10, 100]

In [14]:
mylist

[10, 100, 1000, 2000]

In [15]:
mylist[-2:]  

[1000, 2000]

In [ ]:
mylist

In [ ]:
mylist[:-2]  

In [ ]:
mylist

In [ ]:
mylist[4] 

In [ ]:
mylist

In [16]:
for j in mylist:
    {
        print('jj is equal to :', j) 
    }
    

jj is equal to : 10
jj is equal to : 100
jj is equal to : 1000
jj is equal to : 2000


In [17]:
for j in mylist:
    print('jj is equal to :', j) 

jj is equal to : 10
jj is equal to : 100
jj is equal to : 1000
jj is equal to : 2000


In [18]:
range(5)  #very quick way to creat a set of 5 numbers

range(0, 5)

In [19]:
list(range(5)) 

[0, 1, 2, 3, 4]

In [20]:
list(range(10)) #what actually range 5 does


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
list(range(1,10)) 

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
list(range(10,40,5))  

[10, 15, 20, 25, 30, 35]

In [23]:
list(range(1,10,3)) 

[1, 4, 7]

In [2]:
# ================= IF STATEMENT ======================
# -----(-2),(-1),(0),(1),(2)------------

import numpy as np # numpy is package is a scientific computation, matrix , array  
from numpy.random import randn

In [28]:
randn() 

-0.7369240633868063

In [31]:
# Python Program for simple OTP genertaor
import random as r
# function for otp generation
def otpgen():
    otp=""
    for i in range(2):
        otp+=str(r.randint(1, 5))
    print ("Your One Time Password is ")
    print (otp)
otpgen()

Your One Time Password is 
14


In [5]:
# ========== IF-ELSE STATEMENT ====================
# -----(-2),(-1),(0),(1),(2)------------

#answer = None
x = randn() 
if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
else:
    answer = "Less then 1"
print(x)
print(answer) 

-0.7760316793046214
Less then 1


### what we learned so far -
1.Type of variable
2.Using variable
3.Logical variable and operator
4.while loop
5.For loop
6.if statement, if _ else statement, elif statement
7.random variables: randn()
8.introduce to numpy & pandas

### Fundamentals of python which are used in datascience - 

In [6]:
# List - ordered sequeence of elements & always start with 0
# you can decleare the mixed datatype variables
# List closed in [] bracket

MyFirstList = [5, 50, 67, 2020] 

In [7]:
MyFirstList

[5, 50, 67, 2020]

In [ ]:
type(MyFirstList)


In [ ]:
MysecondList = [2, 5.0,'AMXWAM',True,40+67j] #multiple datatypes you can declared in the list

In [ ]:
MysecondList

In [ ]:
type(MysecondList) 

In [ ]:
amx = ['how are you?',55, (3,4,5)] #list inside the list

In [ ]:
amx

In [8]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana', 'apple'] 

In [9]:
len(fruits)

8

In [10]:
fruits.count('kiwi') 

1

In [11]:
fruits.count('apple')

3

In [12]:
range(15) 

range(0, 15)

In [13]:
list(range(15)) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [ ]:
x = [1,2,3,4,5,6,7]
x

In [14]:
y = list(range(8)) 

In [15]:
y

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
list(range(1,8))

In [16]:
z = list(range(1,8)) 

In [17]:
z

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
a1 = list(range(5,8))
a1

In [ ]:
a2 = list(range(100,120)) 
a2

In [ ]:
a3 = list(range(10,20)) # 10 form right 20-1
a3

In [18]:
a4 = list(range(10,20,5))  # adding 3 steps from 10 to 20

In [19]:
a4

[10, 15]

In [ ]:
xx = list(range(1,5,2)) 

In [ ]:
xx

In [ ]:
a5 = list(range(20,40,5)) 
a5

In [20]:
# Now we can check how to read information from the list
w = ['a','e','i','o','u'] 

In [21]:
w

['a', 'e', 'i', 'o', 'u']

In [22]:
w[0] 

'a'

In [23]:
w[1]

'e'

In [24]:
w[2]

'i'

In [25]:
w

['a', 'e', 'i', 'o', 'u']

In [26]:
#if you have more no of list so how to know how many are there

len(w)  

5

In [27]:
w

['a', 'e', 'i', 'o', 'u']

In [28]:
# a,e,i,o,u
# 0,1,2,3,4 --> left to rigth
# -5,-4,-3,-2,-1 --> right to left

w[-4] 

'e'

In [29]:
w

['a', 'e', 'i', 'o', 'u']

In [30]:
w[:]   

['a', 'e', 'i', 'o', 'u']

In [31]:
w[:-3]  

['a', 'e']

In [32]:
w

['a', 'e', 'i', 'o', 'u']

In [33]:
w[:4] 

['a', 'e', 'i', 'o']

In [34]:
w

['a', 'e', 'i', 'o', 'u']

In [35]:
w[3:] 

['o', 'u']

In [36]:
w[0] 

'a'

In [37]:
# overwrite values
w

['a', 'e', 'i', 'o', 'u']

In [38]:
w[2] = 10
w[2]

10

In [39]:
w

['a', 'e', 10, 'o', 'u']

In [40]:
# slicing : operator
x1 = ['a', 'b', 'c', 'd', 'e' ,'f', 'g', 'h'] 
x1

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [41]:
x1[4:7] #left side part always begins with 0 but right side always have to (no.-1)// 7-1

['e', 'f', 'g']

In [42]:
x1

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [43]:
x1[-5:-3]  

['d', 'e']

In [44]:
x1[-5:-2]  

['d', 'e', 'f']

In [45]:
x1

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [ ]:
x1[2:7] 

In [46]:
x1

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [49]:
x1[-6:-1] 

['c', 'd', 'e', 'f', 'g']

In [50]:
#advanced slicing - [_:_:_] starting,ending,step
#if you specified : one more time then you get 3 spot last step is nothing but step
x1

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [51]:
x1[0:7:2] 

['a', 'c', 'e', 'g']

In [52]:
x1[3:7:3] 

['d', 'g']

In [53]:
x1

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [54]:
x1[3:8:2] 

['d', 'f', 'h']

In [55]:
hallo = ['A','B','C','D','E','F','G','H','I','J']
hallo

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [ ]:
hallo[1:3]    

In [ ]:
hallo[:] 

In [ ]:
hallo[1]  

In [56]:
hallo

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [57]:
hallo[2:] 

['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [58]:
hallo

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [59]:
hallo[:4] 

['A', 'B', 'C', 'D']

In [60]:
hallo

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [61]:
hallo[2:10:2]   

['C', 'E', 'G', 'I']

In [ ]:
hallo

In [ ]:
# --- advanced slicing
hallo[2:9:2] 

In [62]:
hallo

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [63]:
hallo[::-1] # : - PRINT 1ST - LAST, :-1 -> REVERS DIRECT

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [64]:
hallo

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [65]:
hallo[::-3] 

['J', 'G', 'D', 'A']

In [66]:
hallo[::-2] 

['J', 'H', 'F', 'D', 'B']

In [67]:
hallo

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [68]:
hallo[-2:] 

['I', 'J']

In [69]:
hallo

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [70]:
hallo[::2]   # 

['A', 'C', 'E', 'G', 'I']

In [71]:
hallo

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [ ]:
hallo[::-1]  #reversing order print

In [ ]:
hallo

In [72]:
hallo[::-2]  

['J', 'H', 'F', 'D', 'B']

In [ ]:
hallo

In [ ]:
hallo[::-4]  

In [ ]:
hallo

In [ ]:
hallo[:-3]  

In [ ]:
hallo

In [ ]:
hallo[:3]  

In [ ]:
hallo

In [ ]:
hallo[6:0:-2] 

In [ ]:
hallo

In [ ]:
hallo[6:2:-2] 

In [ ]:
hallo

In [ ]:
hallo[7:1:-3]  

In [74]:
#Tuples -- Immutable list or immutable sequence of values

t = (10,20,90) 

In [75]:
t

(10, 20, 90)

In [76]:
t[1] 

20

In [77]:
t[1]=30  #you are unable to change after declaration

TypeError: 'tuple' object does not support item assignment

In [78]:
# Functions in python 

range(20, 31) 


range(20, 31)

In [79]:
list(range(20, 31)) 

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [80]:
mylist1 = list(range(20, 31)) 

In [81]:
mylist1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [82]:
len(mylist1) 

11

In [83]:
type(mylist1) 

list

In [85]:
mylist1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [86]:
max(mylist1) 

30

In [87]:
min(mylist1) 

20

In [88]:
max(1,450,234) 

450

In [89]:
min(1,450,234)

1

In [ ]:
# PACKAGES IN PYTHON
# PACKAGE - BOX, BLENDERS -FUNCTIONS, FRUITS - CLASS,DATA etc... 
# where & how to find the packages - github,googles Q & A query
# Install packages in anaconda prompt
# conda install package name // pip install package name
# import the packages
# from package import module
# give an example of tensorflow how to install in pip 

In [94]:
# NUMPY & ARRAY IN PYTHON
# numpy is the package you have to import 
# list is similar like to array
# numpy is also inbuild array in python

l = [23245, 27, 546, 215, -1234] 
type(l)

list

In [95]:
l

[23245, 27, 546, 215, -1234]

In [91]:
l2 = [23245.5, 27.8, 546.9, 215.2, -1234.0, 'amx', 7.8] 
l2

[23245.5, 27.8, 546.9, 215.2, -1234.0, 'amx', 7.8]

In [92]:
import numpy as np

In [98]:
a = np.array(l) 
type(a)
#type(l)

numpy.ndarray

In [97]:
a

array([23245,    27,   546,   215, -1234])

In [99]:
a1 = np.array(l2) 
a1

array(['23245.5', '27.8', '546.9', '215.2', '-1234.0', 'amx', '7.8'],
      dtype='<U32')

In [ ]:
l1 = [3.0, 4.6] 
l1

In [ ]:
import numpy as np

In [ ]:
a = np.array(l) # list is convert into arrays

In [ ]:
a

In [ ]:
b = np.array(l1)
b

In [ ]:
# what is the main difference between list & array
# you cannot create an array of different data types

b = np.array(12,True)
b

In [ ]:
print(b)  #everything is converted into string

In [100]:
l  #when you select. and then tab you get list of function

[23245, 27, 546, 215, -1234]

In [101]:
l.pop()  

-1234

In [102]:
l

[23245, 27, 546, 215]

In [103]:
l.pop()

215

In [104]:
l

[23245, 27, 546]

In [105]:
a


array([23245,    27,   546,   215, -1234])

In [106]:
a.mean() 

4559.8

In [107]:
a.mode() 


AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [108]:
a.median() 

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [109]:
a

array([23245,    27,   546,   215, -1234])

In [110]:
# slicing array

l

[23245, 27, 546]

In [111]:
l[1:] 

[27, 546]

In [112]:
l[0:2] 

[23245, 27]

In [ ]:
l

In [ ]:
l[:] 

In [ ]:
l[::2] 

In [ ]:
a

In [ ]:
a[2:] 

In [ ]:
a

In [ ]:
a[2:4] 

In [113]:
a

array([23245,    27,   546,   215, -1234])

In [114]:
c = a.copy() # when you create a copy of numpy array, modification can not be done both object array but in list it

In [115]:
c

array([23245,    27,   546,   215, -1234])

In [116]:
a

array([23245,    27,   546,   215, -1234])

In [117]:
c[0] 

23245

In [118]:
c[0] = 20

In [119]:
c

array([   20,    27,   546,   215, -1234])

In [ ]:
a

In [ ]:
a[0] 

In [ ]:
a

In [ ]:
c

In [ ]:
m = [1,2,3]
m[0] 

In [ ]:
m[0]= 81

In [ ]:
m

In [ ]:
n = list.copy(m)  # when you create a copy of list, modification will done both object

In [ ]:
n

In [ ]:
n=m.copy()

In [ ]:
n

In [ ]:
m

# what we learned so far -- 
'''
1> list
2> create some list[],range()
3> using [] bracket
4> slicing list
5> Tuples
6> functions 
7> packages
8> Numpys & Arrays
9> slicing arrays'''

### PYTHOH END - 

-------