In [29]:
import numpy as np

In [30]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [32]:
np.arange(5,10,2)

array([5, 7, 9])

In [33]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [35]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a[0,0]

1

In [37]:
a[0,1]

2

In [38]:
a[1,0]

4

In [39]:
a[1:]

array([[4, 5, 6]])

In [40]:
a[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
a[0:1]

array([[1, 2, 3]])

In [42]:
a[1:2]

array([[4, 5, 6]])

In [43]:
len(a)

2

In [44]:
a.shape

(2, 3)

In [45]:
b=np.array([[5, 7, 3], [2, 4, 6]])
b

array([[5, 7, 3],
       [2, 4, 6]])

In [46]:
a+b

array([[ 6,  9,  6],
       [ 6,  9, 12]])

In [47]:
b-a

array([[ 4,  5,  0],
       [-2, -1,  0]])

In [48]:
a * b

array([[ 5, 14,  9],
       [ 8, 20, 36]])

In [49]:
a=np.array([[3, 1, 4]])
a

array([[3, 1, 4]])

In [50]:
b=np.array([[4,3],[2,5],[6,8]])
b

array([[4, 3],
       [2, 5],
       [6, 8]])

In [51]:
c=np.dot(a,b)
c

array([[38, 46]])

In [52]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
row=4
col=5

In [54]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [56]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [57]:
mat[row,col]

45

In [58]:
mat[row:col]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [105]:
mat[3:8,4:7]

array([[34, 35, 36],
       [44, 45, 46],
       [54, 55, 56],
       [64, 65, 66],
       [74, 75, 76]])

In [107]:
mat[-7:-3,-6:-3]

array([[34, 35, 36],
       [44, 45, 46],
       [54, 55, 56],
       [64, 65, 66]])

In [108]:
mat[6:10,4:7]

array([[64, 65, 66],
       [74, 75, 76],
       [84, 85, 86],
       [94, 95, 96]])

In [110]:
mat[-4:,-6:-3]

array([[64, 65, 66],
       [74, 75, 76],
       [84, 85, 86],
       [94, 95, 96]])

In [76]:
mat[-1:7,-4:10]

array([], shape=(0, 4), dtype=int32)

In [78]:
mat[5:8,6:10]

array([[56, 57, 58, 59],
       [66, 67, 68, 69],
       [76, 77, 78, 79]])

In [79]:
mat[-5:-3,-4:-1]

array([[56, 57, 58],
       [66, 67, 68]])

In [82]:
mat[-6:-3,-8:-6]

array([[42, 43],
       [52, 53],
       [62, 63]])

In [83]:
mat[4:7,2:4]

array([[42, 43],
       [52, 53],
       [62, 63]])

In [84]:
mat[4,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [100]:
mat[-3:,-6:-4]

array([[74, 75],
       [84, 85],
       [94, 95]])

In [101]:
lst=[i for i in range(10)]
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [103]:
lst[4:6]

[4, 5]

In [104]:
mat[-3:,-2:]

array([[78, 79],
       [88, 89],
       [98, 99]])